### ISSUE TITLE
Question on document version

### ISSUE THREAD

**Issue by andre-merzky** [OpenGridForum/Editor#2]
Hi, 

I am a bit confused by the versioning of this document: all three (GFD.174, GFD.207 and this one) are all labeled as Version.1.0.  This being a recommendation track document, I would expect different versions of the spec to be distinguishable for implementors and users (unless this is only an Errata update?).

Along the same lines, it would be fantastic if there was a version which highlights the differences between the previous iteration and this document, or a section which summarizes those differences - I doubt a reader like me who is not familiar with the detail would be able to pick up differences between 200+ page documents within reasonable time, and that information might also   be useful for potential adopters which want to decide to update their implementation?

Thanks for your considerations!
Andre.

**Comment by smhdfdl** [comment]
@andre-merzky Thanks for your comment.  

This is an Errata update primarily, but areas have been reworked to improve readability, following an expert external review. Hence why it is still DFDL 1.0. 

Very good point about the differences. We will publish a change history which lists the changes. The errata are described in [DFDL Experience Document 4](https://redmine.ogf.org/dmsf_files/13384?download=).

**Comment by mbeckerle** [comment]
I have added a GWD-I document 

https://github.com/OpenGridForum/DFDL/blob/master/docs/working-drafts/gwdi-change-history-to-r35.docx 

which contains the change history from GFD.207 to GFD.240.

All changes to technical substance were captured as Errata.

**Comment by mbeckerle** [comment]
I also put a copy of the errata document onto the github location. This is the same errata doc mentioned by smh above, but it is good to have it on github. 

https://github.com/OpenGridForum/DFDL/blob/master/docs/working-drafts/gwde-dfdl-experience-4-v0.10.docx

**Comment by andre-merzky** [comment]
Thank you, that is helpful indeed.
